### ISSUE TITLE
Two identical screens are being created in the same window

### ISSUE THREAD

**Issue by KingofChichizka** [KingofChichizka/Weave#13]
![image](https://github.com/KingofChichizka/Weave/assets/130967018/e6f62e27-6550-448d-8a86-c7b5b12f031a)
It seems to be happening at random, but almost definitive way to make it happen is to press ENTER firstward after opening the app

**Comment by Schnirivadze** [comment]
Try this:
![image](https://github.com/KingofChichizka/Weave/assets/110425232/edabe2c8-a5e1-4710-ae46-8d53b102f49a)
